# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14027344ffd58be1cede77cda37959cc637c3c7feb9144ec3e1098b49072ea98699521f113ed523d327f011d55304c7f7cdd6af8e97e4ec39cc185ba8ec9505d

test:
  secret_key_base: 6421cae1bb156e2a6c1d987f53919960d4cb238572f0be667e0bc7f72d81976d3b048062622f2f99e5231c6737d7d5dc5cb21001777d511662c1518fa5389586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
